name: Release new action version

on:
    push:
      branches: ['main']
    workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: 'pages'
  cancel-in-progress: true
jobs:
    build:
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: oven-sh/setup-bun@v1
              with:
                bun-version: latest
            - run: bun install
            - run: bun check:tsc
            - run: wget https://opendata.tec-wl.be/Current%20GTFS/TEC-GTFS.zip
            - run: unzip -d gtfs TEC-GTFS.zip
            - run: bun generate:geojson
            - run: bun generate:routes
              env:
                VITE_GTFS_KEY: ${{ secrets.VITE_GTFS_KEY }}
                VITE_MAP_KEY: ${{ secrets.VITE_MAP_KEY }}
            - name: Setup Pages
              uses: actions/configure-pages@v4
            - name: Upload artifact
              uses: actions/upload-pages-artifact@v3
              with:
                  # Upload dist folder
                  path: './dist'
            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v4