name: Release new action version

on:
    push:

permissions:
  contents: read
concurrency:
  group: 'pages'
  cancel-in-progress: true
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: oven-sh/setup-bun@v1
              with:
                bun-version: latest
            - run: bun check:tsc